# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "spfyApp"
client_id = "21e70e1c0db438b03bf85dafbc7b9e85"
application_url = "https://examples-gotta-compilation-history.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://examples-gotta-compilation-history.trycloudflare.com/auth/callback",
  "https://examples-gotta-compilation-history.trycloudflare.com/auth/shopify/callback",
  "https://examples-gotta-compilation-history.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "spfy8.myshopify.com"
